version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - IApgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - IAredis:/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - IAqdrant:/qdrant/storage
    restart: unless-stopped
  
  neo4j:
    image: neo4j:5.20
    container_name: neo4j-kg
    restart: unless-stopped
    ports:
      - "7474:7474" #ui
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123       # change this in production
      NEO4J_dbms_security_auth__enabled: "true"
      NEO4J_dbms_default__database: neo4j
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_heap_max__size: 4G
      NEO4J_dbms_memory_pagecache_size: 2G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins

volumes:
  IApgdata:
  IAredis:
  IAqdrant:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
